### ISSUE TITLE
[Bug]: spm_full_example001

### ISSUE THREAD

**Issue by cyril-data** [Inria-Empenn/BEP028_BIDSprov#4]
### batch name and line

nidm example : [batch.m](https://github.com/incf-nidash/nidmresults-examples/blob/master/spm_full_example001/batch.m) : 

```
matlabbatch{4}.spm.stats.results.spmmat(1) = cfg_dep('Contrast Manager: SPM.mat File', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{4}.spm.stats.results.conspec.titlestr = '';
matlabbatch{4}.spm.stats.results.conspec.contrasts = Inf;
matlabbatch{4}.spm.stats.results.conspec.threshdesc = 'none';
matlabbatch{4}.spm.stats.results.conspec.thresh = 0.001;
matlabbatch{4}.spm.stats.results.conspec.extent = 0;
matlabbatch{4}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{4}.spm.stats.results.units = 1;
matlabbatch{4}.spm.stats.results.print = 'pdf';
matlabbatch{4}.spm.stats.results.write.none = 1;
```

### What happened?

The bug : 

 `python -m bids_prov.spm_parser --input_file ../nidmresults-examples/spm_full_example001/batch.m`

```
file= ../nidmresults-examples/spm_full_example001/batch.m
Traceback (most recent call last):
  File "/home/cregan/Documents/CODE/Projets/3_FWIN/BIDS-prov/FORK_BEP028_BIDSpro/launch_multiple_spm.py", line 66, in <module>
    main()
  File "/home/cregan/Documents/CODE/Projets/3_FWIN/BIDS-prov/FORK_BEP028_BIDSpro/launch_multiple_spm.py", line 52, in main
    spm_to_bids_prov(root + "/" + str(file), conf.CONTEXT_URL, output_file=output_jsonld,
  File "/home/cregan/Documents/CODE/Projets/3_FWIN/BIDS-prov/FORK_BEP028_BIDSpro/bids_prov/spm_parser.py", line 349, in spm_to_bids_prov
    records = get_records(tasks, verbose=verbose)
  File "/home/cregan/Documents/CODE/Projets/3_FWIN/BIDS-prov/FORK_BEP028_BIDSpro/bids_prov/spm_parser.py", line 321, in get_records
    if entity["@id"] not in entities_ids:
KeyError: '@id'
```

### Describe the expected ground-truth ?

The expected ground-truth : 

### What soft is concerned

spm

**Comment by cmaumet** [comment]
Thanks @cyril-data! The batch indeed seems incomplete (starting with an activity `{4}`): https://github.com/incf-nidash/nidmresults-examples/blob/master/spm_full_example001/batch.m so I am happy with us ignoring it in the CI.
